package com.gtnhkanban.network.message;

public enum RequestType {
    LIST_PROJECTS,
    CREATE_PROJECT,
    ADD_MEMBER,
    REMOVE_MEMBER,
    FETCH_BOARD,
    CREATE_CARD,
    UPDATE_CARD,
    DELETE_PROJECT,
    DELETE_CARD,
    MOVE_CARD,
    ADD_REQUIREMENT,
    SET_REQUIREMENT_COMPLETE,
    DELETE_REQUIREMENT,
    SET_REQUIREMENT_QUANTITY,
    SET_CARD_ASSIGNED,
    EXPAND_REQUIREMENT,
    UPLOAD_BREAKDOWN,
    SET_PROJECT_ICON,
    ADD_TASK,
    SET_TASK_DONE,
    DELETE_TASK,
    ADD_COMMENT,
    DELETE_COMMENT,
    SAVE_SETTINGS,
    LIST_PLAYER_NAMES
}
